"""API view exchanging a mobile one-time token for the Django session cookie.

Counterpart of `core.authentication.views`: the OIDC callback hands a one-time
token to the mobile app via deep link, and the app calls this endpoint from its
native HTTP layer to obtain the session cookie used by all subsequent API calls.
"""

import base64
import hashlib
import secrets
from importlib import import_module

from django.conf import settings
from django.contrib.auth import SESSION_KEY
from django.core.cache import cache
from django.middleware.csrf import get_token

from drf_spectacular.utils import extend_schema
from rest_framework import status
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.views import APIView

from core.authentication.views import MOBILE_AUTH_TOKEN_CACHE_PREFIX


def _s256(code_verifier):
    """Compute the RFC 7636 S256 transform of a PKCE code verifier."""
    digest = hashlib.sha256(code_verifier.encode("utf-8")).digest()
    return base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")


class MobileSessionExchangeView(APIView):
    """Exchange the one-time token minted by the OIDC callback for a session cookie.

    Anonymous by design: the request is authenticated by the single-use token
    and the PKCE verifier generated by the app before opening the system browser.
    """

    authentication_classes = []
    permission_classes = [AllowAny]

    # Excluded from the OpenAPI schema: this endpoint is part of the mobile
    # auth bootstrap (like /authenticate/), not of the Orval-generated client.
    @extend_schema(exclude=True)
    def post(self, request):
        """Verify the token and PKCE verifier, then attach the session to the response."""
        token = request.data.get("token", "")
        code_verifier = request.data.get("code_verifier", "")
        if not token or not code_verifier:
            return Response(
                {"detail": "Missing token or code_verifier."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        cache_key = f"{MOBILE_AUTH_TOKEN_CACHE_PREFIX}:{token}"
        payload = cache.get(cache_key)
        # Single use: drop the token before verifying it so a failed attempt
        # cannot be retried with another verifier.
        cache.delete(cache_key)
        if payload is None or not secrets.compare_digest(
            _s256(code_verifier), payload["code_challenge"]
        ):
            return Response(
                {"detail": "Invalid or expired token."},
                status=status.HTTP_403_FORBIDDEN,
            )

        engine = import_module(settings.SESSION_ENGINE)
        session = engine.SessionStore(payload["session_key"])
        if session.get(SESSION_KEY) is None:
            return Response(
                {"detail": "Session expired."},
                status=status.HTTP_403_FORBIDDEN,
            )

        # Attach the session to the underlying HttpRequest (not the DRF proxy)
        # so SessionMiddleware emits the Set-Cookie header on this response.
        http_request = request._request  # noqa: SLF001
        http_request.session = session
        http_request.session.modified = True
        csrf_token = get_token(http_request)

        return Response({"csrf_token": csrf_token})
